-- #############################################################################
-- Hearth — combined setup.sql
-- Auto-generated by concatenating supabase/migrations/*.sql in filename order.
-- (No standalone supabase/seed.sql exists; seed data is migration 0003.)
-- The SQL below is unmodified; only these "-- file:" boundary comments were
-- inserted. Run this whole file against your Supabase project's SQL editor.
-- #############################################################################


-- =====================================================================
-- file: supabase/migrations/0001_initial_schema.sql
-- =====================================================================
-- =============================================================================
-- Hearth — initial schema (Phase 1)
-- Screens 1-5: Onboarding, Home Profile, Dashboard, Report Issue, Find a Pro.
-- Phase 2 tables (improvements, intent_signals, documents) are included so the
-- foreign keys and RLS story are coherent from day one, but no UI ships yet.
-- =============================================================================

create extension if not exists "pgcrypto";

-- -----------------------------------------------------------------------------
-- users — mirrors auth.users (Supabase Auth owns identity/credentials).
-- A row is created automatically on signup via the trigger below.
-- -----------------------------------------------------------------------------
create table public.users (
  id          uuid primary key references auth.users (id) on delete cascade,
  email       text unique,
  phone       text,
  full_name   text,
  created_at  timestamptz not null default now()
);

-- Auto-provision a public.users row when a new auth user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, phone)
  values (new.id, new.email, new.phone)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- -----------------------------------------------------------------------------
-- properties — the claimed home; links to the parcel layer.
-- -----------------------------------------------------------------------------
create table public.properties (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references public.users (id) on delete cascade,
  parcel_id           text,            -- FK to Layer-1 parcel data (Regrid / county)
  address_line1       text not null,
  city                text,
  state               text,
  zip                 text,
  year_built          int,
  sqft                int,
  beds                int,
  baths               numeric(3,1),
  lot_size_sqft       int,
  property_type       text,            -- single_family, condo, townhouse, ...
  purchase_date       date,
  ownership_verified  boolean not null default false,
  created_at          timestamptz not null default now()
);
create index properties_user_id_idx on public.properties (user_id);
create index properties_parcel_id_idx on public.properties (parcel_id);

-- -----------------------------------------------------------------------------
-- system_lifespans — reference defaults so the dashboard can predict work
-- without the owner having to know typical lifespans. Seeded in 0003.
-- -----------------------------------------------------------------------------
create table public.system_lifespans (
  system_type             text primary key,
  expected_lifespan_years int not null,
  label                   text not null
);

-- -----------------------------------------------------------------------------
-- home_systems — the condition core.
-- -----------------------------------------------------------------------------
create table public.home_systems (
  id                       uuid primary key default gen_random_uuid(),
  property_id              uuid not null references public.properties (id) on delete cascade,
  system_type              text not null,  -- roof, hvac, water_heater, electrical_panel, plumbing, windows, foundation, appliance
  material_or_model        text,
  install_year             int,
  last_serviced            date,
  condition_rating         int check (condition_rating between 1 and 5),
  expected_lifespan_years  int,            -- defaults from system_lifespans by type
  notes                    text,
  created_at               timestamptz not null default now()
);
create index home_systems_property_id_idx on public.home_systems (property_id);

-- -----------------------------------------------------------------------------
-- maintenance_tasks — dashboard items.
-- -----------------------------------------------------------------------------
create table public.maintenance_tasks (
  id            uuid primary key default gen_random_uuid(),
  property_id   uuid not null references public.properties (id) on delete cascade,
  system_id     uuid references public.home_systems (id) on delete set null,
  title         text not null,
  due_date      date,
  recurrence    text not null default 'none',  -- none, monthly, seasonal, annual
  status        text not null default 'open',  -- open, done, snoozed
  completed_at  timestamptz,
  created_at    timestamptz not null default now()
);
create index maintenance_tasks_property_id_idx on public.maintenance_tasks (property_id);

-- -----------------------------------------------------------------------------
-- issues — reported problems; condition signal + contractor-lead trigger.
-- -----------------------------------------------------------------------------
create table public.issues (
  id                 uuid primary key default gen_random_uuid(),
  property_id        uuid not null references public.properties (id) on delete cascade,
  system_id          uuid references public.home_systems (id) on delete set null,
  category           text not null,    -- roof, plumbing, electrical, hvac, structural, other
  severity           text not null,    -- low, medium, urgent
  description        text,
  status             text not null default 'open',  -- open, resolved
  converted_to_lead  boolean not null default false,
  created_at         timestamptz not null default now()
);
create index issues_property_id_idx on public.issues (property_id);

-- -----------------------------------------------------------------------------
-- photos — polymorphic attachments (issue / improvement / system).
-- -----------------------------------------------------------------------------
create table public.photos (
  id            uuid primary key default gen_random_uuid(),
  property_id   uuid not null references public.properties (id) on delete cascade,
  related_type  text not null,         -- issue, improvement, system
  related_id    uuid not null,
  url           text not null,
  uploaded_at   timestamptz not null default now()
);
create index photos_related_idx on public.photos (related_type, related_id);
create index photos_property_id_idx on public.photos (property_id);

-- -----------------------------------------------------------------------------
-- improvements — remodel log (Phase 2 UI, schema present now).
-- -----------------------------------------------------------------------------
create table public.improvements (
  id                uuid primary key default gen_random_uuid(),
  property_id       uuid not null references public.properties (id) on delete cascade,
  system_id         uuid references public.home_systems (id) on delete set null,
  improvement_type  text not null,     -- roof_replacement, kitchen_remodel, addition, ...
  description       text,
  completed_date    date,
  cost              numeric(12,2),
  permit_id         text,              -- FK to detected permit (Layer 2)
  source            text not null default 'self_reported',  -- self_reported, permit_matched
  created_at        timestamptz not null default now()
);
create index improvements_property_id_idx on public.improvements (property_id);

-- -----------------------------------------------------------------------------
-- contractors — vetted directory (shared reference data, not user-owned).
-- -----------------------------------------------------------------------------
create table public.contractors (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  license_number  text,
  categories      text[],              -- {roofing, plumbing, ...}
  service_area    text,
  contact_email   text,
  contact_phone   text,
  vetted          boolean not null default false,
  rating          numeric(2,1),
  created_at      timestamptz not null default now()
);
create index contractors_categories_idx on public.contractors using gin (categories);

-- -----------------------------------------------------------------------------
-- contractor_leads — the revenue object.
-- -----------------------------------------------------------------------------
create table public.contractor_leads (
  id            uuid primary key default gen_random_uuid(),
  property_id   uuid not null references public.properties (id) on delete cascade,
  issue_id      uuid references public.issues (id) on delete set null,
  contractor_id uuid references public.contractors (id) on delete set null,
  category      text not null,
  status        text not null default 'new',  -- new, sent, accepted, closed, lost
  payout_amount numeric(10,2),
  created_at    timestamptz not null default now()
);
create index contractor_leads_property_id_idx on public.contractor_leads (property_id);
create index contractor_leads_contractor_id_idx on public.contractor_leads (contractor_id);

-- -----------------------------------------------------------------------------
-- intent_signals — sell-readiness, kept separate for governance/consent.
-- (Phase 2 UI; schema present now.)
-- -----------------------------------------------------------------------------
create table public.intent_signals (
  id              uuid primary key default gen_random_uuid(),
  property_id     uuid not null references public.properties (id) on delete cascade,
  signal_type     text not null,       -- stay_timeline, wants_valuation, considering_selling
  value           text,
  shared_consent  boolean not null default false,
  captured_at     timestamptz not null default now()
);
create index intent_signals_property_id_idx on public.intent_signals (property_id);

-- -----------------------------------------------------------------------------
-- documents — vault (Phase 2 UI; schema present now).
-- -----------------------------------------------------------------------------
create table public.documents (
  id            uuid primary key default gen_random_uuid(),
  property_id   uuid not null references public.properties (id) on delete cascade,
  doc_type      text,                  -- warranty, manual, receipt, inspection_report
  file_url      text not null,
  uploaded_at   timestamptz not null default now()
);
create index documents_property_id_idx on public.documents (property_id);


-- =====================================================================
-- file: supabase/migrations/0002_rls_policies.sql
-- =====================================================================
-- =============================================================================
-- Hearth — Row-Level Security
-- Default-deny. An owner can touch only rows belonging to a property they own.
-- Reference data (contractors, system_lifespans) is read-only to any signed-in
-- user. Writes to those tables happen via service-role/admin only.
-- =============================================================================

-- Helper: does the current user own this property?
create or replace function public.owns_property(p_property_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.properties p
    where p.id = p_property_id and p.user_id = auth.uid()
  );
$$;

-- Enable RLS everywhere.
alter table public.users             enable row level security;
alter table public.properties        enable row level security;
alter table public.home_systems      enable row level security;
alter table public.maintenance_tasks enable row level security;
alter table public.issues            enable row level security;
alter table public.photos            enable row level security;
alter table public.improvements      enable row level security;
alter table public.contractor_leads  enable row level security;
alter table public.intent_signals    enable row level security;
alter table public.documents         enable row level security;
alter table public.contractors       enable row level security;
alter table public.system_lifespans  enable row level security;

-- ---- users: self only -------------------------------------------------------
create policy "users self select" on public.users
  for select using (id = auth.uid());
create policy "users self update" on public.users
  for update using (id = auth.uid()) with check (id = auth.uid());

-- ---- properties: owner only -------------------------------------------------
create policy "properties owner select" on public.properties
  for select using (user_id = auth.uid());
create policy "properties owner insert" on public.properties
  for insert with check (user_id = auth.uid());
create policy "properties owner update" on public.properties
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "properties owner delete" on public.properties
  for delete using (user_id = auth.uid());

-- ---- child tables: gated through property ownership --------------------------
-- A single all-command policy per table keeps this readable; owns_property()
-- enforces select/insert/update/delete uniformly.
create policy "home_systems owner all" on public.home_systems
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "maintenance_tasks owner all" on public.maintenance_tasks
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "issues owner all" on public.issues
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "photos owner all" on public.photos
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "improvements owner all" on public.improvements
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "contractor_leads owner all" on public.contractor_leads
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "intent_signals owner all" on public.intent_signals
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "documents owner all" on public.documents
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

-- ---- reference data: read-only to any authenticated user --------------------
create policy "contractors read" on public.contractors
  for select to authenticated using (true);

create policy "system_lifespans read" on public.system_lifespans
  for select to authenticated using (true);


-- =====================================================================
-- file: supabase/migrations/0003_seed_reference_data.sql
-- =====================================================================
-- =============================================================================
-- Hearth — seed reference data
-- Typical-lifespan defaults (power the dashboard) + a few demo contractors so
-- Screen 5 has something to match against locally.
-- =============================================================================

insert into public.system_lifespans (system_type, expected_lifespan_years, label) values
  ('roof',             22, 'Roof'),
  ('hvac',             18, 'HVAC system'),
  ('water_heater',     11, 'Water heater'),
  ('electrical_panel', 35, 'Electrical panel'),
  ('plumbing',         50, 'Plumbing'),
  ('windows',          25, 'Windows'),
  ('foundation',       75, 'Foundation'),
  ('appliance',        12, 'Major appliance')
on conflict (system_type) do update
  set expected_lifespan_years = excluded.expected_lifespan_years,
      label = excluded.label;

-- Demo vetted contractors. Replace with real, verified partners before launch.
insert into public.contractors (name, license_number, categories, service_area, contact_email, contact_phone, vetted, rating) values
  ('Summit Roofing Co.',      'CA-RF-100231', array['roof']::text[],                 'Bay Area, CA',   'leads@summitroofing.example',   '+1-415-555-0142', true, 4.8),
  ('Delta Plumbing & Drain',  'CA-PL-553102', array['plumbing']::text[],             'Bay Area, CA',   'dispatch@deltaplumb.example',   '+1-415-555-0177', true, 4.6),
  ('BrightSpark Electric',    'CA-EL-882014', array['electrical']::text[],           'Bay Area, CA',   'hello@brightspark.example',     '+1-510-555-0190', true, 4.7),
  ('ClimateRight HVAC',       'CA-HV-220985', array['hvac']::text[],                 'Bay Area, CA',   'service@climateright.example',  '+1-650-555-0123', true, 4.5),
  ('Foundation First',        'CA-GC-310777', array['structural']::text[],           'Bay Area, CA',   'info@foundationfirst.example',  '+1-408-555-0156', true, 4.4),
  ('AllTrades Home Services', 'CA-GC-411902', array['roof','plumbing','hvac','electrical','structural','other']::text[], 'Bay Area, CA', 'quotes@alltrades.example', '+1-415-555-0188', true, 4.3)
on conflict do nothing;


-- =====================================================================
-- file: supabase/migrations/0004_storage.sql
-- =====================================================================
-- =============================================================================
-- Hearth — storage for issue/improvement/system photos and the docs vault.
-- Files are namespaced by property id as the first path segment:
--   home-photos/<property_id>/<uuid>.jpg
-- so RLS can check ownership from the object path.
-- =============================================================================

insert into storage.buckets (id, name, public)
values ('home-photos', 'home-photos', true)
on conflict (id) do nothing;

-- Owners can read/write only objects under a property they own. The first
-- folder segment of the object name is the property id.
create policy "home-photos owner read" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'home-photos'
    and public.owns_property( (storage.foldername(name))[1]::uuid )
  );

create policy "home-photos owner insert" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'home-photos'
    and public.owns_property( (storage.foldername(name))[1]::uuid )
  );

create policy "home-photos owner delete" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'home-photos'
    and public.owns_property( (storage.foldername(name))[1]::uuid )
  );


-- =====================================================================
-- file: supabase/migrations/0005_contractor_side.sql
-- =====================================================================
-- =============================================================================
-- Hearth — contractor (pro) side
-- Real per-contractor accounts + a lead "inbox" with per-lead fees.
--
-- Design: a lead is a frozen PACKET. When a homeowner requests a pro we snapshot
-- the name/contact/address/issue onto contractor_leads, so a contractor reads
-- ONLY contractor_leads — never the homeowner's private properties/issues/users.
-- =============================================================================

-- ---- link a contractor company to an auth user -----------------------------
alter table public.contractors
  add column if not exists user_id uuid references auth.users (id) on delete set null;
create index if not exists contractors_user_id_idx on public.contractors (user_id);

-- ---- lead packet: snapshot + per-lead fee + simulated billing ---------------
alter table public.contractor_leads
  add column if not exists homeowner_name    text,
  add column if not exists homeowner_email   text,
  add column if not exists homeowner_phone   text,
  add column if not exists property_address  text,
  add column if not exists issue_description text,
  add column if not exists issue_severity    text,
  add column if not exists timing            text,
  add column if not exists paid              boolean not null default false,
  add column if not exists paid_at           timestamptz;
-- payout_amount (existing) is the per-lead fee the contractor owes us.

-- ---- RLS: a contractor manages their own company row ------------------------
create policy "contractors insert own" on public.contractors
  for insert to authenticated
  with check (user_id = auth.uid());

create policy "contractors update own" on public.contractors
  for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ---- RLS: a contractor sees / updates only leads assigned to them -----------
-- These are ADDITIONAL permissive policies; they OR with the existing
-- "contractor_leads owner all" homeowner policy, so both parties see the lead.
create policy "leads contractor select" on public.contractor_leads
  for select to authenticated
  using (
    contractor_id in (select id from public.contractors where user_id = auth.uid())
  );

create policy "leads contractor update" on public.contractor_leads
  for update to authenticated
  using (
    contractor_id in (select id from public.contractors where user_id = auth.uid())
  )
  with check (
    contractor_id in (select id from public.contractors where user_id = auth.uid())
  );


-- =====================================================================
-- file: supabase/migrations/0006_lead_previews.sql
-- =====================================================================
-- Public, PII-free preview of available leads (contact stays locked behind signup).
create or replace view public.lead_previews as
select
  l.id,
  l.category,
  l.issue_severity                                          as severity,
  l.payout_amount                                           as lead_fee,
  nullif(trim(split_part(l.property_address, ',', 2)), '')  as area,
  l.created_at
from public.contractor_leads l
where l.status = 'new';

grant select on public.lead_previews to anon, authenticated;
