-- #############################################################################
-- Hearth — combined setup.sql
-- Auto-generated by concatenating supabase/migrations/*.sql in filename order.
-- (No standalone supabase/seed.sql exists; seed data is migration 0003.)
-- The SQL below is unmodified; only these "-- file:" boundary comments were
-- inserted. Run this whole file against your Supabase project's SQL editor.
-- #############################################################################


-- =====================================================================
-- file: supabase/migrations/0001_initial_schema.sql
-- =====================================================================
-- =============================================================================
-- Hearth — initial schema (Phase 1)
-- Screens 1-5: Onboarding, Home Profile, Dashboard, Report Issue, Find a Pro.
-- Phase 2 tables (improvements, intent_signals, documents) are included so the
-- foreign keys and RLS story are coherent from day one, but no UI ships yet.
-- =============================================================================

create extension if not exists "pgcrypto";

-- -----------------------------------------------------------------------------
-- users — mirrors auth.users (Supabase Auth owns identity/credentials).
-- A row is created automatically on signup via the trigger below.
-- -----------------------------------------------------------------------------
create table public.users (
  id          uuid primary key references auth.users (id) on delete cascade,
  email       text unique,
  phone       text,
  full_name   text,
  notification_prefs jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

-- Auto-provision a public.users row when a new auth user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, phone)
  values (new.id, new.email, new.phone)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- -----------------------------------------------------------------------------
-- properties — the claimed home; links to the parcel layer.
-- -----------------------------------------------------------------------------
create table public.properties (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references public.users (id) on delete cascade,
  parcel_id           text,            -- FK to Layer-1 parcel data (Regrid / county)
  address_line1       text not null,
  city                text,
  state               text,
  zip                 text,
  year_built          int,
  sqft                int,
  beds                int,
  baths               numeric(3,1),
  lot_size_sqft       int,
  property_type       text,            -- single_family, condo, townhouse, ...
  purchase_date       date,
  ownership_verified  boolean not null default false,
  created_at          timestamptz not null default now()
);
create index properties_user_id_idx on public.properties (user_id);
create index properties_parcel_id_idx on public.properties (parcel_id);

-- -----------------------------------------------------------------------------
-- system_lifespans — reference defaults so the dashboard can predict work
-- without the owner having to know typical lifespans. Seeded in 0003.
-- -----------------------------------------------------------------------------
create table public.system_lifespans (
  system_type             text primary key,
  expected_lifespan_years int not null,
  label                   text not null
);

-- -----------------------------------------------------------------------------
-- home_systems — the condition core.
-- -----------------------------------------------------------------------------
create table public.home_systems (
  id                       uuid primary key default gen_random_uuid(),
  property_id              uuid not null references public.properties (id) on delete cascade,
  system_type              text not null,  -- roof, hvac, water_heater, electrical_panel, plumbing, windows, foundation, appliance
  material_or_model        text,
  install_year             int,
  last_serviced            date,
  condition_rating         int check (condition_rating between 1 and 5),
  expected_lifespan_years  int,            -- defaults from system_lifespans by type
  notes                    text,
  created_at               timestamptz not null default now()
);
create index home_systems_property_id_idx on public.home_systems (property_id);

-- -----------------------------------------------------------------------------
-- maintenance_tasks — dashboard items.
-- -----------------------------------------------------------------------------
create table public.maintenance_tasks (
  id            uuid primary key default gen_random_uuid(),
  property_id   uuid not null references public.properties (id) on delete cascade,
  system_id     uuid references public.home_systems (id) on delete set null,
  title         text not null,
  due_date      date,
  recurrence    text not null default 'none',  -- none, monthly, seasonal, annual
  status        text not null default 'open',  -- open, done, snoozed
  completed_at  timestamptz,
  created_at    timestamptz not null default now()
);
create index maintenance_tasks_property_id_idx on public.maintenance_tasks (property_id);

-- -----------------------------------------------------------------------------
-- issues — reported problems; condition signal + contractor-lead trigger.
-- -----------------------------------------------------------------------------
create table public.issues (
  id                 uuid primary key default gen_random_uuid(),
  property_id        uuid not null references public.properties (id) on delete cascade,
  system_id          uuid references public.home_systems (id) on delete set null,
  category           text not null,    -- roof, plumbing, electrical, hvac, structural, other
  severity           text not null,    -- low, medium, urgent
  description        text,
  status             text not null default 'open',  -- open, resolved
  converted_to_lead  boolean not null default false,
  created_at         timestamptz not null default now()
);
create index issues_property_id_idx on public.issues (property_id);

-- -----------------------------------------------------------------------------
-- photos — polymorphic attachments (issue / improvement / system).
-- -----------------------------------------------------------------------------
create table public.photos (
  id            uuid primary key default gen_random_uuid(),
  property_id   uuid not null references public.properties (id) on delete cascade,
  related_type  text not null,         -- issue, improvement, system
  related_id    uuid not null,
  url           text not null,
  uploaded_at   timestamptz not null default now()
);
create index photos_related_idx on public.photos (related_type, related_id);
create index photos_property_id_idx on public.photos (property_id);

-- -----------------------------------------------------------------------------
-- improvements — remodel log (Phase 2 UI, schema present now).
-- -----------------------------------------------------------------------------
create table public.improvements (
  id                uuid primary key default gen_random_uuid(),
  property_id       uuid not null references public.properties (id) on delete cascade,
  system_id         uuid references public.home_systems (id) on delete set null,
  improvement_type  text not null,     -- roof_replacement, kitchen_remodel, addition, ...
  description       text,
  completed_date    date,
  cost              numeric(12,2),
  permit_id         text,              -- FK to detected permit (Layer 2)
  source            text not null default 'self_reported',  -- self_reported, permit_matched
  created_at        timestamptz not null default now()
);
create index improvements_property_id_idx on public.improvements (property_id);

-- -----------------------------------------------------------------------------
-- contractors — vetted directory (shared reference data, not user-owned).
-- -----------------------------------------------------------------------------
create table public.contractors (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  license_number  text,
  categories      text[],              -- {roofing, plumbing, ...}
  service_area    text,
  contact_email   text,
  contact_phone   text,
  vetted          boolean not null default false,
  rating          numeric(2,1),
  created_at      timestamptz not null default now()
);
create index contractors_categories_idx on public.contractors using gin (categories);

-- -----------------------------------------------------------------------------
-- contractor_leads — the revenue object.
-- -----------------------------------------------------------------------------
create table public.contractor_leads (
  id            uuid primary key default gen_random_uuid(),
  property_id   uuid not null references public.properties (id) on delete cascade,
  issue_id      uuid references public.issues (id) on delete set null,
  contractor_id uuid references public.contractors (id) on delete set null,
  category      text not null,
  status        text not null default 'new',  -- new, sent, accepted, closed, lost
  payout_amount numeric(10,2),
  created_at    timestamptz not null default now()
);
create index contractor_leads_property_id_idx on public.contractor_leads (property_id);
create index contractor_leads_contractor_id_idx on public.contractor_leads (contractor_id);

-- -----------------------------------------------------------------------------
-- intent_signals — sell-readiness, kept separate for governance/consent.
-- (Phase 2 UI; schema present now.)
-- -----------------------------------------------------------------------------
create table public.intent_signals (
  id              uuid primary key default gen_random_uuid(),
  property_id     uuid not null references public.properties (id) on delete cascade,
  signal_type     text not null,       -- stay_timeline, wants_valuation, considering_selling
  value           text,
  shared_consent  boolean not null default false,
  captured_at     timestamptz not null default now()
);
create index intent_signals_property_id_idx on public.intent_signals (property_id);

-- -----------------------------------------------------------------------------
-- documents — vault (Phase 2 UI; schema present now).
-- -----------------------------------------------------------------------------
create table public.documents (
  id            uuid primary key default gen_random_uuid(),
  property_id   uuid not null references public.properties (id) on delete cascade,
  doc_type      text,                  -- warranty, manual, receipt, inspection_report
  file_url      text not null,
  -- Facts the vision model reads off the document, so they can auto-fill the
  -- digital twin (home_systems) instead of the owner retyping them.
  title            text,
  brand            text,
  model            text,
  install_year     integer,
  warranty_expires date,
  system_type      text,               -- which home system this doc belongs to
  summary          text,
  applied_at       timestamptz,        -- when the facts were pushed to home_systems
  uploaded_at   timestamptz not null default now()
);
create index documents_property_id_idx on public.documents (property_id);

-- -----------------------------------------------------------------------------
-- support_messages - in-app contact form. A homeowner can create and read their
-- own; the team reads all through the service role.
-- -----------------------------------------------------------------------------
create table public.support_messages (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid references auth.users (id) on delete set null,
  name         text,
  email        text,
  phone        text,
  message      text not null,
  status       text not null default 'open',
  created_at   timestamptz not null default now()
);
create index support_messages_user_id_idx on public.support_messages (user_id);
alter table public.support_messages enable row level security;
create policy "support self insert" on public.support_messages
  for insert to authenticated with check (user_id = auth.uid());
create policy "support self select" on public.support_messages
  for select to authenticated using (user_id = auth.uid());


-- =====================================================================
-- file: supabase/migrations/0002_rls_policies.sql
-- =====================================================================
-- =============================================================================
-- Hearth — Row-Level Security
-- Default-deny. An owner can touch only rows belonging to a property they own.
-- Reference data (contractors, system_lifespans) is read-only to any signed-in
-- user. Writes to those tables happen via service-role/admin only.
-- =============================================================================

-- Helper: does the current user own this property?
create or replace function public.owns_property(p_property_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.properties p
    where p.id = p_property_id and p.user_id = auth.uid()
  );
$$;

-- Enable RLS everywhere.
alter table public.users             enable row level security;
alter table public.properties        enable row level security;
alter table public.home_systems      enable row level security;
alter table public.maintenance_tasks enable row level security;
alter table public.issues            enable row level security;
alter table public.photos            enable row level security;
alter table public.improvements      enable row level security;
alter table public.contractor_leads  enable row level security;
alter table public.intent_signals    enable row level security;
alter table public.documents         enable row level security;
alter table public.contractors       enable row level security;
alter table public.system_lifespans  enable row level security;

-- ---- users: self only -------------------------------------------------------
create policy "users self select" on public.users
  for select using (id = auth.uid());
create policy "users self update" on public.users
  for update using (id = auth.uid()) with check (id = auth.uid());

-- ---- properties: owner only -------------------------------------------------
create policy "properties owner select" on public.properties
  for select using (user_id = auth.uid());
create policy "properties owner insert" on public.properties
  for insert with check (user_id = auth.uid());
create policy "properties owner update" on public.properties
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "properties owner delete" on public.properties
  for delete using (user_id = auth.uid());

-- ---- child tables: gated through property ownership --------------------------
-- A single all-command policy per table keeps this readable; owns_property()
-- enforces select/insert/update/delete uniformly.
create policy "home_systems owner all" on public.home_systems
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "maintenance_tasks owner all" on public.maintenance_tasks
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "issues owner all" on public.issues
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "photos owner all" on public.photos
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "improvements owner all" on public.improvements
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "contractor_leads owner all" on public.contractor_leads
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "intent_signals owner all" on public.intent_signals
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

create policy "documents owner all" on public.documents
  for all using (public.owns_property(property_id))
  with check (public.owns_property(property_id));

-- ---- reference data: read-only to any authenticated user --------------------
create policy "contractors read" on public.contractors
  for select to authenticated using (true);

create policy "system_lifespans read" on public.system_lifespans
  for select to authenticated using (true);


-- =====================================================================
-- file: supabase/migrations/0003_seed_reference_data.sql
-- =====================================================================
-- =============================================================================
-- Hearth — seed reference data
-- Typical-lifespan defaults (power the dashboard) + a few demo contractors so
-- Screen 5 has something to match against locally.
-- =============================================================================

insert into public.system_lifespans (system_type, expected_lifespan_years, label) values
  ('roof',             22, 'Roof'),
  ('hvac',             18, 'HVAC system'),
  ('water_heater',     11, 'Water heater'),
  ('electrical_panel', 35, 'Electrical panel'),
  ('plumbing',         50, 'Plumbing'),
  ('windows',          25, 'Windows'),
  ('foundation',       75, 'Foundation'),
  ('appliance',        12, 'Major appliance')
on conflict (system_type) do update
  set expected_lifespan_years = excluded.expected_lifespan_years,
      label = excluded.label;

-- Demo vetted contractors. Replace with real, verified partners before launch.
insert into public.contractors (name, license_number, categories, service_area, contact_email, contact_phone, vetted, rating) values
  ('Summit Roofing Co.',      'CA-RF-100231', array['roof']::text[],                 'Bay Area, CA',   'leads@summitroofing.example',   '+1-415-555-0142', true, 4.8),
  ('Delta Plumbing & Drain',  'CA-PL-553102', array['plumbing']::text[],             'Bay Area, CA',   'dispatch@deltaplumb.example',   '+1-415-555-0177', true, 4.6),
  ('BrightSpark Electric',    'CA-EL-882014', array['electrical']::text[],           'Bay Area, CA',   'hello@brightspark.example',     '+1-510-555-0190', true, 4.7),
  ('ClimateRight HVAC',       'CA-HV-220985', array['hvac']::text[],                 'Bay Area, CA',   'service@climateright.example',  '+1-650-555-0123', true, 4.5),
  ('Foundation First',        'CA-GC-310777', array['structural']::text[],           'Bay Area, CA',   'info@foundationfirst.example',  '+1-408-555-0156', true, 4.4),
  ('AllTrades Home Services', 'CA-GC-411902', array['roof','plumbing','hvac','electrical','structural','other']::text[], 'Bay Area, CA', 'quotes@alltrades.example', '+1-415-555-0188', true, 4.3)
on conflict do nothing;


-- =====================================================================
-- file: supabase/migrations/0004_storage.sql
-- =====================================================================
-- =============================================================================
-- Hearth — storage for issue/improvement/system photos and the docs vault.
-- Files are namespaced by property id as the first path segment:
--   home-photos/<property_id>/<uuid>.jpg
-- so RLS can check ownership from the object path.
-- =============================================================================

insert into storage.buckets (id, name, public)
values ('home-photos', 'home-photos', true)
on conflict (id) do nothing;

-- Owners can read/write only objects under a property they own. The first
-- folder segment of the object name is the property id.
create policy "home-photos owner read" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'home-photos'
    and public.owns_property( (storage.foldername(name))[1]::uuid )
  );

create policy "home-photos owner insert" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'home-photos'
    and public.owns_property( (storage.foldername(name))[1]::uuid )
  );

create policy "home-photos owner delete" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'home-photos'
    and public.owns_property( (storage.foldername(name))[1]::uuid )
  );


-- =====================================================================
-- file: supabase/migrations/0005_contractor_side.sql
-- =====================================================================
-- =============================================================================
-- Hearth — contractor (pro) side
-- Real per-contractor accounts + a lead "inbox" with per-lead fees.
--
-- Design: a lead is a frozen PACKET. When a homeowner requests a pro we snapshot
-- the name/contact/address/issue onto contractor_leads, so a contractor reads
-- ONLY contractor_leads — never the homeowner's private properties/issues/users.
-- =============================================================================

-- ---- link a contractor company to an auth user -----------------------------
alter table public.contractors
  add column if not exists user_id uuid references auth.users (id) on delete set null;
create index if not exists contractors_user_id_idx on public.contractors (user_id);

-- ---- lead packet: snapshot + per-lead fee + simulated billing ---------------
alter table public.contractor_leads
  add column if not exists homeowner_name    text,
  add column if not exists homeowner_email   text,
  add column if not exists homeowner_phone   text,
  add column if not exists property_address  text,
  add column if not exists issue_description text,
  add column if not exists issue_severity    text,
  add column if not exists timing            text,
  add column if not exists paid              boolean not null default false,
  add column if not exists paid_at           timestamptz;
-- payout_amount (existing) is the per-lead fee the contractor owes us.

-- ---- RLS: a contractor manages their own company row ------------------------
create policy "contractors insert own" on public.contractors
  for insert to authenticated
  with check (user_id = auth.uid());

create policy "contractors update own" on public.contractors
  for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ---- RLS: a contractor sees / updates only leads assigned to them -----------
-- These are ADDITIONAL permissive policies; they OR with the existing
-- "contractor_leads owner all" homeowner policy, so both parties see the lead.
create policy "leads contractor select" on public.contractor_leads
  for select to authenticated
  using (
    contractor_id in (select id from public.contractors where user_id = auth.uid())
  );

create policy "leads contractor update" on public.contractor_leads
  for update to authenticated
  using (
    contractor_id in (select id from public.contractors where user_id = auth.uid())
  )
  with check (
    contractor_id in (select id from public.contractors where user_id = auth.uid())
  );


-- =====================================================================
-- file: supabase/migrations/0006_lead_previews.sql
-- =====================================================================
-- =============================================================================
-- Hearth — public lead previews
-- Lets contractors see THAT demand exists (category, coarse area, severity, fee)
-- before creating an account, while homeowner PII stays locked behind signup.
--
-- This view intentionally exposes only non-PII columns and is readable by anon.
-- It runs with the view owner's rights, so it surfaces all "new" leads for the
-- teaser — but never name / email / phone / street address.
-- =============================================================================

create or replace view public.lead_previews as
select
  l.id,
  l.category,
  l.issue_severity                                          as severity,
  l.payout_amount                                           as lead_fee,
  nullif(trim(split_part(l.property_address, ',', 2)), '')  as area,
  l.created_at
from public.contractor_leads l
where l.status = 'new';

grant select on public.lead_previews to anon, authenticated;


-- =====================================================================
-- file: supabase/migrations/0007_messages.sql
-- =====================================================================
-- =============================================================================
-- Hearth — lead messaging (homeowner <-> contractor)
-- A thread is attached to a contractor_lead. Only the homeowner who owns the
-- lead's property and the contractor assigned to it can read/post.
-- =============================================================================

create table public.messages (
  id           uuid primary key default gen_random_uuid(),
  lead_id      uuid not null references public.contractor_leads (id) on delete cascade,
  sender_role  text not null,  -- homeowner, contractor
  sender_id    uuid references auth.users (id) on delete set null,
  body         text not null,
  created_at   timestamptz not null default now()
);
create index messages_lead_idx on public.messages (lead_id, created_at);

alter table public.messages enable row level security;

-- Can the current user see this lead (either side of it)?
create or replace function public.can_access_lead(p_lead_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.contractor_leads l
    where l.id = p_lead_id
      and (
        public.owns_property(l.property_id)
        or l.contractor_id in (
          select id from public.contractors where user_id = auth.uid()
        )
      )
  );
$$;

create policy "messages select" on public.messages
  for select to authenticated
  using (public.can_access_lead(lead_id));

create policy "messages insert" on public.messages
  for insert to authenticated
  with check (public.can_access_lead(lead_id) and sender_id = auth.uid());


-- =====================================================================
-- file: supabase/migrations/0008_wallet.sql
-- =====================================================================
-- =============================================================================
-- Hearth — contractor prepaid wallet
-- Pros add funds, then PAY per lead (from their balance) to unlock it — which
-- reveals the homeowner's contact and enables messaging. Replaces "balance
-- owed" so a pro can't grab a lead and skip paying.
-- `contractor_leads.paid` (from 0005) now means "unlocked/charged".
-- =============================================================================

alter table public.contractors
  add column if not exists balance numeric(10,2) not null default 0;

create table if not exists public.wallet_transactions (
  id            uuid primary key default gen_random_uuid(),
  contractor_id uuid not null references public.contractors (id) on delete cascade,
  amount        numeric(10,2) not null,   -- + deposit, - lead charge
  kind          text not null,            -- deposit, lead_charge
  lead_id       uuid references public.contractor_leads (id) on delete set null,
  created_at    timestamptz not null default now()
);
create index if not exists wallet_tx_contractor_idx
  on public.wallet_transactions (contractor_id, created_at desc);

alter table public.wallet_transactions enable row level security;
create policy "wallet tx owner select" on public.wallet_transactions
  for select to authenticated
  using (contractor_id in (select id from public.contractors where user_id = auth.uid()));

-- Add funds (simulated — no real charge yet). UI enforces $5–$100; enforced here too.
create or replace function public.add_deposit(p_amount numeric)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_cid uuid;
begin
  if p_amount < 5 or p_amount > 100 then
    raise exception 'Deposit must be between $5 and $100';
  end if;
  select id into v_cid from public.contractors where user_id = auth.uid();
  if v_cid is null then raise exception 'Not a contractor'; end if;
  update public.contractors set balance = balance + p_amount where id = v_cid;
  insert into public.wallet_transactions (contractor_id, amount, kind)
    values (v_cid, p_amount, 'deposit');
end;
$$;

-- Pay a lead's fee from the wallet to unlock contact + messaging.
create or replace function public.unlock_lead(p_lead_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_cid uuid; v_fee numeric; v_balance numeric; v_paid boolean;
begin
  select id, balance into v_cid, v_balance
    from public.contractors where user_id = auth.uid();
  if v_cid is null then raise exception 'Not a contractor'; end if;

  select payout_amount, paid into v_fee, v_paid
    from public.contractor_leads
    where id = p_lead_id and contractor_id = v_cid;
  if v_fee is null then raise exception 'Lead not found'; end if;
  if v_paid then return; end if;
  if v_balance < v_fee then
    raise exception 'Insufficient balance — add funds first';
  end if;

  update public.contractors set balance = balance - v_fee where id = v_cid;
  update public.contractor_leads set paid = true, paid_at = now() where id = p_lead_id;
  insert into public.wallet_transactions (contractor_id, amount, kind, lead_id)
    values (v_cid, -v_fee, 'lead_charge', p_lead_id);
end;
$$;

grant execute on function public.add_deposit(numeric) to authenticated;
grant execute on function public.unlock_lead(uuid) to authenticated;


-- =====================================================================
-- file: supabase/migrations/0009_social.sql
-- =====================================================================
-- =============================================================================
-- Hearth — social & engagement tables
--   reviews            homeowner rates a contractor after a finished job
--   reports            either party flags a conversation for the Hearth team
--   message_reactions  emoji reactions on a chat message
--   lead_reads         per-side read receipts for a lead's thread
--
-- These were originally created by hand in the Supabase dashboard; this brings
-- them under version control. Written idempotently (IF NOT EXISTS / drop policy
-- first) so it is safe to run against an existing database as well as a fresh
-- one. Depends on can_access_lead() (0007) and owns_property() (0002).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Reviews
-- ---------------------------------------------------------------------------
create table if not exists public.reviews (
  id            uuid primary key default gen_random_uuid(),
  lead_id       uuid not null references public.contractor_leads (id) on delete cascade,
  contractor_id uuid not null references public.contractors (id) on delete cascade,
  property_id   uuid references public.properties (id) on delete set null,
  rating        smallint not null check (rating between 1 and 5),
  comment       text,
  created_at    timestamptz not null default now()
);
create index if not exists reviews_contractor_idx on public.reviews (contractor_id);
create index if not exists reviews_lead_idx on public.reviews (lead_id);

alter table public.reviews enable row level security;

-- Either party to the lead can read it; a contractor can also read reviews
-- written about them.
drop policy if exists "reviews select" on public.reviews;
create policy "reviews select" on public.reviews
  for select to authenticated
  using (
    public.can_access_lead(lead_id)
    or contractor_id in (select id from public.contractors where user_id = auth.uid())
  );

-- Only someone on the lead (the homeowner) can leave the review.
drop policy if exists "reviews insert" on public.reviews;
create policy "reviews insert" on public.reviews
  for insert to authenticated
  with check (public.can_access_lead(lead_id));

-- ---------------------------------------------------------------------------
-- Reports
-- ---------------------------------------------------------------------------
create table if not exists public.reports (
  id            uuid primary key default gen_random_uuid(),
  lead_id       uuid not null references public.contractor_leads (id) on delete cascade,
  reporter_id   uuid references auth.users (id) on delete set null,
  reporter_role text not null,           -- homeowner, contractor
  reason        text,
  created_at    timestamptz not null default now()
);
create index if not exists reports_lead_idx on public.reports (lead_id, created_at desc);

alter table public.reports enable row level security;

-- Reporters can file a report and see their own; the Hearth team reviews
-- everything via the service role (which bypasses RLS).
drop policy if exists "reports insert" on public.reports;
create policy "reports insert" on public.reports
  for insert to authenticated
  with check (public.can_access_lead(lead_id) and reporter_id = auth.uid());

drop policy if exists "reports select" on public.reports;
create policy "reports select" on public.reports
  for select to authenticated
  using (reporter_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Message reactions
-- ---------------------------------------------------------------------------
create table if not exists public.message_reactions (
  id          uuid primary key default gen_random_uuid(),
  message_id  uuid not null references public.messages (id) on delete cascade,
  lead_id     uuid not null references public.contractor_leads (id) on delete cascade,
  user_id     uuid references auth.users (id) on delete set null,
  emoji       text not null,
  created_at  timestamptz not null default now()
);
-- One reaction of a given emoji per user per message (supports the toggle).
create unique index if not exists message_reactions_unique
  on public.message_reactions (message_id, user_id, emoji);
create index if not exists message_reactions_lead_idx
  on public.message_reactions (lead_id);

alter table public.message_reactions enable row level security;

drop policy if exists "reactions select" on public.message_reactions;
create policy "reactions select" on public.message_reactions
  for select to authenticated
  using (public.can_access_lead(lead_id));

drop policy if exists "reactions insert" on public.message_reactions;
create policy "reactions insert" on public.message_reactions
  for insert to authenticated
  with check (public.can_access_lead(lead_id) and user_id = auth.uid());

drop policy if exists "reactions delete" on public.message_reactions;
create policy "reactions delete" on public.message_reactions
  for delete to authenticated
  using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Lead read receipts
-- ---------------------------------------------------------------------------
create table if not exists public.lead_reads (
  id         uuid primary key default gen_random_uuid(),
  lead_id    uuid not null references public.contractor_leads (id) on delete cascade,
  role       text not null,          -- homeowner, contractor
  read_at    timestamptz not null default now()
);
-- One row per side; the app upserts on (lead_id, role).
create unique index if not exists lead_reads_unique
  on public.lead_reads (lead_id, role);

alter table public.lead_reads enable row level security;

drop policy if exists "lead_reads select" on public.lead_reads;
create policy "lead_reads select" on public.lead_reads
  for select to authenticated
  using (public.can_access_lead(lead_id));

-- Upsert needs both insert and update permission.
drop policy if exists "lead_reads insert" on public.lead_reads;
create policy "lead_reads insert" on public.lead_reads
  for insert to authenticated
  with check (public.can_access_lead(lead_id));

drop policy if exists "lead_reads update" on public.lead_reads;
create policy "lead_reads update" on public.lead_reads
  for update to authenticated
  using (public.can_access_lead(lead_id))
  with check (public.can_access_lead(lead_id));


-- =====================================================================
-- file: supabase/migrations/0010_wallet_v2.sql
-- =====================================================================
-- =============================================================================
-- Hearth — dual-balance wallet (cash + bonus) with deposit-match tiers.
-- All money is integer CENTS. No floats anywhere.
-- Replaces the old single-balance wallet (contractors.balance + add_deposit /
-- unlock_lead). Those are dropped at the bottom.
-- =============================================================================

-- ---- Config (single row; tunable without a redeploy) ------------------------
create table if not exists public.wallet_config (
  id                      int primary key default 1,
  min_bonus_deposit_cents bigint  not null default 25000,  -- $250
  bonus_expiry_days       int     not null default 60,
  spend_cash_first        boolean not null default true,
  constraint wallet_config_single_row check (id = 1)
);
insert into public.wallet_config (id) values (1) on conflict (id) do nothing;

-- ---- Deposit match tiers ----------------------------------------------------
create table if not exists public.deposit_tiers (
  id        uuid primary key default gen_random_uuid(),
  min_cents bigint not null,
  max_cents bigint,            -- null = no upper bound
  bonus_pct int    not null
);
insert into public.deposit_tiers (min_cents, max_cents, bonus_pct)
select v.min_cents, v.max_cents, v.bonus_pct
from (values
  (25000,  49999::bigint, 10),
  (50000,  99999::bigint, 15),
  (100000, null::bigint,  20)
) as v(min_cents, max_cents, bonus_pct)
where not exists (select 1 from public.deposit_tiers);

-- ---- Wallets ----------------------------------------------------------------
create table if not exists public.wallets (
  id                  uuid primary key default gen_random_uuid(),
  contractor_id       uuid not null unique references public.contractors (id) on delete cascade,
  cash_balance_cents  bigint not null default 0,
  bonus_balance_cents bigint not null default 0,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- ---- Bonus grants (per-tranche expiry, drawn FIFO) --------------------------
create table if not exists public.bonus_grants (
  id              uuid primary key default gen_random_uuid(),
  wallet_id       uuid not null references public.wallets (id) on delete cascade,
  amount_cents    bigint not null,
  remaining_cents bigint not null,
  expires_at      timestamptz not null,
  created_at      timestamptz not null default now()
);
create index if not exists bonus_grants_wallet_idx
  on public.bonus_grants (wallet_id, expires_at);

-- ---- Ledger (append-only). Replace the old simple table. --------------------
drop table if exists public.wallet_transactions cascade;
create table public.wallet_transactions (
  id                        uuid primary key default gen_random_uuid(),
  wallet_id                 uuid not null references public.wallets (id) on delete cascade,
  type                      text not null,   -- deposit | bonus_grant | lead_charge | bonus_expiry | adjustment
  cash_delta_cents          bigint not null default 0,
  bonus_delta_cents         bigint not null default 0,
  cash_balance_after_cents  bigint not null,
  bonus_balance_after_cents bigint not null,
  lead_id                   uuid references public.contractor_leads (id) on delete set null,
  note                      text,
  created_at                timestamptz not null default now()
);
create index if not exists wallet_tx_wallet_idx
  on public.wallet_transactions (wallet_id, created_at desc);

-- ---- RLS: owners can read their own wallet data; config/tiers are public ----
alter table public.wallets enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.bonus_grants enable row level security;
alter table public.wallet_config enable row level security;
alter table public.deposit_tiers enable row level security;

drop policy if exists "wallets owner read" on public.wallets;
create policy "wallets owner read" on public.wallets for select to authenticated
  using (contractor_id in (select id from public.contractors where user_id = auth.uid()));

drop policy if exists "wallet tx owner read" on public.wallet_transactions;
create policy "wallet tx owner read" on public.wallet_transactions for select to authenticated
  using (wallet_id in (
    select w.id from public.wallets w
    join public.contractors c on c.id = w.contractor_id
    where c.user_id = auth.uid()
  ));

drop policy if exists "bonus grants owner read" on public.bonus_grants;
create policy "bonus grants owner read" on public.bonus_grants for select to authenticated
  using (wallet_id in (
    select w.id from public.wallets w
    join public.contractors c on c.id = w.contractor_id
    where c.user_id = auth.uid()
  ));

drop policy if exists "wallet config read" on public.wallet_config;
create policy "wallet config read" on public.wallet_config for select to authenticated using (true);
drop policy if exists "deposit tiers read" on public.deposit_tiers;
create policy "deposit tiers read" on public.deposit_tiers for select to authenticated using (true);

-- ---- Functions --------------------------------------------------------------

create or replace function public.get_or_create_wallet(p_contractor uuid)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_id uuid;
begin
  select id into v_id from wallets where contractor_id = p_contractor;
  if v_id is null then
    insert into wallets (contractor_id) values (p_contractor) returning id into v_id;
  end if;
  return v_id;
end; $$;

-- Bonus (cents) earned on a deposit, per the tier table.
create or replace function public.bonus_for_deposit(p_deposit_cents bigint)
returns bigint language sql stable set search_path = public as $$
  select coalesce((
    select (p_deposit_cents * bonus_pct) / 100
    from deposit_tiers
    where p_deposit_cents >= min_cents
      and (max_cents is null or p_deposit_cents <= max_cents)
    order by min_cents desc
    limit 1
  ), 0);
$$;

-- Apply a successful deposit: credit cash, grant bonus, create grant + ledger.
-- Called by the Stripe webhook (service role).
create or replace function public.apply_deposit(p_contractor uuid, p_deposit_cents bigint)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_wallet uuid;
  v_bonus bigint;
  v_days int;
  v_cash_after bigint;
  v_bonus_after bigint;
begin
  v_wallet := get_or_create_wallet(p_contractor);
  v_bonus := bonus_for_deposit(p_deposit_cents);
  select bonus_expiry_days into v_days from wallet_config where id = 1;

  update wallets
     set cash_balance_cents = cash_balance_cents + p_deposit_cents, updated_at = now()
   where id = v_wallet
   returning cash_balance_cents, bonus_balance_cents into v_cash_after, v_bonus_after;
  insert into wallet_transactions
    (wallet_id, type, cash_delta_cents, cash_balance_after_cents, bonus_balance_after_cents, note)
    values (v_wallet, 'deposit', p_deposit_cents, v_cash_after, v_bonus_after, 'Deposit');

  if v_bonus > 0 then
    update wallets
       set bonus_balance_cents = bonus_balance_cents + v_bonus, updated_at = now()
     where id = v_wallet
     returning cash_balance_cents, bonus_balance_cents into v_cash_after, v_bonus_after;
    insert into bonus_grants (wallet_id, amount_cents, remaining_cents, expires_at)
      values (v_wallet, v_bonus, v_bonus, now() + (v_days || ' days')::interval);
    insert into wallet_transactions
      (wallet_id, type, bonus_delta_cents, cash_balance_after_cents, bonus_balance_after_cents, note)
      values (v_wallet, 'bonus_grant', v_bonus, v_cash_after, v_bonus_after, 'Deposit bonus');
  end if;
end; $$;

-- Charge a lead to the caller's wallet (cash first, then bonus FIFO).
-- Returns true if charged/already paid, false if balance is insufficient.
-- Derives the contractor from auth.uid() and the price from the lead, so a
-- caller can't charge someone else or fake a price.
create or replace function public.charge_lead(p_lead uuid)
returns boolean language plpgsql security definer set search_path = public as $$
declare
  v_contractor uuid; v_wallet uuid;
  v_price bigint; v_paid boolean;
  v_cash bigint; v_bonus bigint;
  v_from_cash bigint; v_from_bonus bigint;
  v_remaining bigint; v_grant record;
  v_cash_first boolean;
  v_cash_after bigint; v_bonus_after bigint;
begin
  select id into v_contractor from contractors where user_id = auth.uid();
  if v_contractor is null then raise exception 'Not a contractor'; end if;

  select round(payout_amount * 100)::bigint, paid into v_price, v_paid
    from contractor_leads where id = p_lead and contractor_id = v_contractor;
  if v_price is null then raise exception 'Lead not found'; end if;
  if v_paid then return true; end if;

  v_wallet := get_or_create_wallet(v_contractor);
  select cash_balance_cents, bonus_balance_cents into v_cash, v_bonus
    from wallets where id = v_wallet;
  if coalesce(v_cash,0) + coalesce(v_bonus,0) < v_price then
    return false;  -- insufficient: caller should prompt a deposit
  end if;

  select spend_cash_first into v_cash_first from wallet_config where id = 1;

  if v_cash_first then
    v_from_cash := least(v_cash, v_price);
    v_from_bonus := v_price - v_from_cash;
  else
    v_from_bonus := least(v_bonus, v_price);
    v_from_cash := v_price - v_from_bonus;
  end if;

  if v_from_bonus > 0 then
    v_remaining := v_from_bonus;
    for v_grant in
      select * from bonus_grants
      where wallet_id = v_wallet and remaining_cents > 0 and expires_at > now()
      order by expires_at asc, created_at asc
    loop
      exit when v_remaining <= 0;
      if v_grant.remaining_cents >= v_remaining then
        update bonus_grants set remaining_cents = remaining_cents - v_remaining where id = v_grant.id;
        v_remaining := 0;
      else
        v_remaining := v_remaining - v_grant.remaining_cents;
        update bonus_grants set remaining_cents = 0 where id = v_grant.id;
      end if;
    end loop;
    if v_remaining > 0 then return false; end if;  -- safety
  end if;

  update wallets
     set cash_balance_cents  = cash_balance_cents  - v_from_cash,
         bonus_balance_cents = bonus_balance_cents - v_from_bonus,
         updated_at = now()
   where id = v_wallet
   returning cash_balance_cents, bonus_balance_cents into v_cash_after, v_bonus_after;

  update contractor_leads set paid = true, paid_at = now() where id = p_lead;

  insert into wallet_transactions
    (wallet_id, type, cash_delta_cents, bonus_delta_cents,
     cash_balance_after_cents, bonus_balance_after_cents, lead_id, note)
    values (v_wallet, 'lead_charge', -v_from_cash, -v_from_bonus,
            v_cash_after, v_bonus_after, p_lead, 'Lead unlocked');

  return true;
end; $$;

-- Daily job: expire bonus tranches past their date.
create or replace function public.expire_bonus()
returns void language plpgsql security definer set search_path = public as $$
declare v_grant record; v_cash_after bigint; v_bonus_after bigint;
begin
  for v_grant in
    select * from bonus_grants where expires_at < now() and remaining_cents > 0
  loop
    update wallets
       set bonus_balance_cents = bonus_balance_cents - v_grant.remaining_cents, updated_at = now()
     where id = v_grant.wallet_id
     returning cash_balance_cents, bonus_balance_cents into v_cash_after, v_bonus_after;
    insert into wallet_transactions
      (wallet_id, type, bonus_delta_cents, cash_balance_after_cents, bonus_balance_after_cents, note)
      values (v_grant.wallet_id, 'bonus_expiry', -v_grant.remaining_cents,
              v_cash_after, v_bonus_after, 'Bonus expired');
    update bonus_grants set remaining_cents = 0 where id = v_grant.id;
  end loop;
end; $$;

-- Note: CREATE FUNCTION already grants EXECUTE to PUBLIC (incl. authenticated),
-- so no explicit grants are needed. apply_deposit / expire_bonus are called by
-- the service role (webhook / scheduled job).

-- ---- Retire the old single-balance wallet -----------------------------------
drop function if exists public.add_deposit(numeric);
drop function if exists public.unlock_lead(uuid);
-- (contractors.balance is left in place but unused; safe to drop later.)


-- =====================================================================
-- file: supabase/migrations/0011_user_full_name_on_signup.sql
-- =====================================================================
-- =============================================================================
-- Hearth — carry the user's name from sign-up into their profile row.
--
-- handle_new_user() previously copied only id/email/phone, so full_name stayed
-- null until the user edited their account — which left the toolbar showing
-- their email. Sign-up now collects a name and passes it in the auth metadata
-- (raw_user_meta_data.full_name); copy it through on account creation.
--
-- Idempotent (create or replace); safe to re-run.
-- =============================================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, phone, full_name)
  values (
    new.id,
    new.email,
    new.phone,
    nullif(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;


-- =====================================================================
-- file: supabase/migrations/0012_job_board.sql
-- =====================================================================
-- =============================================================================
-- Hearth — job board (Indeed-style)
--
-- A homeowner POSTS A JOB: a contractor_leads row with contractor_id = NULL.
-- Pros PAY THE PER-CATEGORY FEE TO APPLY, creating a lead_applications row.
-- The homeowner REVIEWS applicants and CHOOSES one; the chosen pro is assigned
-- the lead and unlocked (gets contact + chat). Apply fees are non-refundable, so
-- the other applicants keep their 'applied' status with no refund.
--
-- Privacy: open jobs are read by ALL matching pros, but contractor_leads carries
-- the homeowner's contact snapshot, so pros never read that table directly for an
-- open job. They go through SECURITY DEFINER functions that return only safe,
-- non-contact columns until they are chosen (which assigns them the lead).
-- =============================================================================

-- ---- Applications -----------------------------------------------------------
create table if not exists public.lead_applications (
  id            uuid primary key default gen_random_uuid(),
  lead_id       uuid not null references public.contractor_leads (id) on delete cascade,
  contractor_id uuid not null references public.contractors (id) on delete cascade,
  message       text,
  status        text not null default 'applied'
                  check (status in ('applied', 'chosen', 'declined')),
  fee_cents     bigint not null default 0,
  created_at    timestamptz not null default now(),
  unique (lead_id, contractor_id)
);
create index if not exists lead_applications_lead_idx
  on public.lead_applications (lead_id);
create index if not exists lead_applications_contractor_idx
  on public.lead_applications (contractor_id);

alter table public.lead_applications enable row level security;

-- A contractor reads their own applications.
drop policy if exists "applications contractor read" on public.lead_applications;
create policy "applications contractor read" on public.lead_applications
  for select to authenticated
  using (contractor_id in (
    select id from public.contractors where user_id = auth.uid()
  ));

-- A homeowner reads the applications on jobs they posted.
drop policy if exists "applications homeowner read" on public.lead_applications;
create policy "applications homeowner read" on public.lead_applications
  for select to authenticated
  using (lead_id in (
    select cl.id from public.contractor_leads cl
    where public.owns_property(cl.property_id)
  ));
-- No insert/update policies: writes go through the SECURITY DEFINER functions
-- below, which also handle billing and authorization.

-- ---- Open jobs a pro can apply to (no contact, category-matched) -------------
create or replace function public.open_jobs_for_me()
returns table (
  id                uuid,
  category          text,
  timing            text,
  issue_description text,
  issue_severity    text,
  payout_amount     numeric,
  created_at        timestamptz,
  application_count bigint
) language sql security definer set search_path = public as $$
  select cl.id, cl.category, cl.timing, cl.issue_description,
         cl.issue_severity, cl.payout_amount, cl.created_at,
         (select count(*) from lead_applications la where la.lead_id = cl.id)
  from contractor_leads cl
  join contractors c on c.user_id = auth.uid()
  where cl.contractor_id is null
    and cl.status = 'new'
    and (c.categories is null or cl.category = any (c.categories))
    and not exists (
      select 1 from lead_applications la
      where la.lead_id = cl.id and la.contractor_id = c.id
    )
  order by cl.created_at desc;
$$;

-- ---- A pro's own applications (safe job fields; no contact) ------------------
create or replace function public.my_applications()
returns table (
  application_id    uuid,
  lead_id           uuid,
  status            text,
  fee_cents         bigint,
  applied_at        timestamptz,
  category          text,
  timing            text,
  issue_description text,
  issue_severity    text,
  payout_amount     numeric,
  lead_status       text
) language sql security definer set search_path = public as $$
  select la.id, la.lead_id, la.status, la.fee_cents, la.created_at,
         cl.category, cl.timing, cl.issue_description, cl.issue_severity,
         cl.payout_amount, cl.status
  from lead_applications la
  join contractors c on c.id = la.contractor_id and c.user_id = auth.uid()
  join contractor_leads cl on cl.id = la.lead_id
  order by la.created_at desc;
$$;

-- ---- Apply to a job: charge the per-category fee (cash first, then bonus) ----
-- Returns true if applied (or already applied), false if the balance is short.
create or replace function public.apply_to_lead(p_lead uuid, p_message text)
returns boolean language plpgsql security definer set search_path = public as $$
declare
  v_contractor uuid; v_wallet uuid; v_cats text[];
  v_lead_contractor uuid; v_status text; v_category text; v_price bigint;
  v_cash bigint; v_bonus bigint; v_from_cash bigint; v_from_bonus bigint;
  v_remaining bigint; v_grant record; v_cash_first boolean;
  v_cash_after bigint; v_bonus_after bigint;
begin
  select id, categories into v_contractor, v_cats
    from contractors where user_id = auth.uid();
  if v_contractor is null then raise exception 'Not a contractor'; end if;

  select contractor_id, status, category, round(payout_amount * 100)::bigint
    into v_lead_contractor, v_status, v_category, v_price
    from contractor_leads where id = p_lead;
  if v_category is null then raise exception 'Job not found'; end if;
  if v_lead_contractor is not null then return false; end if;  -- already assigned
  if v_status <> 'new' then return false; end if;              -- not open
  if v_cats is not null and not (v_category = any (v_cats)) then
    raise exception 'Job is not in your categories';
  end if;
  if exists (
    select 1 from lead_applications
    where lead_id = p_lead and contractor_id = v_contractor
  ) then
    return true;  -- idempotent: already applied
  end if;

  v_wallet := get_or_create_wallet(v_contractor);
  select cash_balance_cents, bonus_balance_cents into v_cash, v_bonus
    from wallets where id = v_wallet;
  if coalesce(v_cash, 0) + coalesce(v_bonus, 0) < v_price then
    return false;  -- insufficient: prompt a deposit
  end if;

  select spend_cash_first into v_cash_first from wallet_config where id = 1;
  if v_cash_first then
    v_from_cash := least(v_cash, v_price);
    v_from_bonus := v_price - v_from_cash;
  else
    v_from_bonus := least(v_bonus, v_price);
    v_from_cash := v_price - v_from_bonus;
  end if;

  if v_from_bonus > 0 then
    v_remaining := v_from_bonus;
    for v_grant in
      select * from bonus_grants
      where wallet_id = v_wallet and remaining_cents > 0 and expires_at > now()
      order by expires_at asc, created_at asc
    loop
      exit when v_remaining <= 0;
      if v_grant.remaining_cents >= v_remaining then
        update bonus_grants set remaining_cents = remaining_cents - v_remaining
         where id = v_grant.id;
        v_remaining := 0;
      else
        v_remaining := v_remaining - v_grant.remaining_cents;
        update bonus_grants set remaining_cents = 0 where id = v_grant.id;
      end if;
    end loop;
    if v_remaining > 0 then return false; end if;  -- safety
  end if;

  update wallets
     set cash_balance_cents  = cash_balance_cents  - v_from_cash,
         bonus_balance_cents = bonus_balance_cents - v_from_bonus,
         updated_at = now()
   where id = v_wallet
   returning cash_balance_cents, bonus_balance_cents into v_cash_after, v_bonus_after;

  insert into lead_applications (lead_id, contractor_id, message, status, fee_cents)
    values (p_lead, v_contractor, nullif(btrim(p_message), ''), 'applied', v_price);

  insert into wallet_transactions
    (wallet_id, type, cash_delta_cents, bonus_delta_cents,
     cash_balance_after_cents, bonus_balance_after_cents, lead_id, note)
    values (v_wallet, 'apply_fee', -v_from_cash, -v_from_bonus,
            v_cash_after, v_bonus_after, p_lead, 'Applied to job');

  return true;
end; $$;

-- ---- Homeowner chooses an applicant -----------------------------------------
-- Assigns + unlocks the chosen pro; declines the rest (no refund).
create or replace function public.choose_applicant(p_application uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_lead uuid; v_contractor uuid; v_owns boolean;
begin
  select lead_id, contractor_id into v_lead, v_contractor
    from lead_applications where id = p_application;
  if v_lead is null then raise exception 'Application not found'; end if;

  select public.owns_property(cl.property_id) into v_owns
    from contractor_leads cl where cl.id = v_lead;
  if not coalesce(v_owns, false) then raise exception 'Not your job'; end if;

  update contractor_leads
     set contractor_id = v_contractor, status = 'accepted',
         paid = true, paid_at = now()
   where id = v_lead;

  update lead_applications set status = 'chosen' where id = p_application;
  update lead_applications set status = 'declined'
   where lead_id = v_lead and id <> p_application and status = 'applied';
end; $$;


-- =====================================================================
-- file: supabase/migrations/0013_realtime.sql
-- =====================================================================
-- =============================================================================
-- Hearth — enable Supabase Realtime on the tables the UI subscribes to.
--
-- Realtime only pushes changes for tables that are in the `supabase_realtime`
-- publication. `messages` is usually already there (the chat uses it), but we
-- add it idempotently alongside the leads + applications tables so the contractor
-- Leads board and the unread-message badge update instantly instead of waiting
-- on their poll fallbacks.
-- =============================================================================

do $$
declare
  t text;
begin
  foreach t in array array[
    'contractor_leads',
    'lead_applications',
    'messages'
  ] loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;

-- Full row image on update/delete so realtime filters (e.g. contractor_id) match
-- reliably even when the changed columns aren't the filtered ones.
alter table public.contractor_leads replica identity full;
alter table public.lead_applications replica identity full;


-- =====================================================================
-- file: supabase/migrations/0014_learning_requests.sql
-- =====================================================================
-- =============================================================================
-- Hearth — learning requests. When a homeowner can't find an answer in Learn,
-- they ask for a guide and we capture it (to prioritize what to add next).
-- =============================================================================

create table if not exists public.learning_requests (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid references auth.users (id) on delete set null,
  question   text not null,
  created_at timestamptz not null default now()
);

alter table public.learning_requests enable row level security;

drop policy if exists "learning_requests insert own" on public.learning_requests;
create policy "learning_requests insert own" on public.learning_requests
  for insert to authenticated with check (user_id = auth.uid());

drop policy if exists "learning_requests read own" on public.learning_requests;
create policy "learning_requests read own" on public.learning_requests
  for select to authenticated using (user_id = auth.uid());


-- =====================================================================
-- file: supabase/migrations/0015_other_service_matching.sql
-- =====================================================================
-- =============================================================================
-- Hearth — match jobs to a pro's custom (free-text) services by keyword.
--
-- Canonical-category jobs already match on exact equality (cl.category =
-- any(c.categories)). On top of that, this rewrites open_jobs_for_me() so ANY
-- open job also surfaces to a pro whose custom (free-text) service appears in the
-- job description or fuzzy-matches it (trigram word similarity, e.g. "gutter
-- cleaning" ~ "I need my gutters cleaned"). It runs regardless of the job's
-- category, because homeowners bucket jobs imperfectly — a gutter job might be
-- filed under Roof, Cleaning, or Other — so a niche pro should still find it.
-- The trigram threshold keeps it specific, so feeds aren't flooded.
--
-- pg_trgm provides word_similarity(); it lives in the `extensions` schema on
-- Supabase, so the function's search_path includes it.
-- =============================================================================

create extension if not exists pg_trgm with schema extensions;

create or replace function public.open_jobs_for_me()
returns table (
  id                uuid,
  category          text,
  timing            text,
  issue_description text,
  issue_severity    text,
  payout_amount     numeric,
  created_at        timestamptz,
  application_count bigint
) language sql security definer set search_path = public, extensions as $$
  select cl.id, cl.category, cl.timing, cl.issue_description,
         cl.issue_severity, cl.payout_amount, cl.created_at,
         (select count(*) from lead_applications la where la.lead_id = cl.id)
  from contractor_leads cl
  join contractors c on c.user_id = auth.uid()
  where cl.contractor_id is null
    and cl.status = 'new'
    and (
      c.categories is null
      -- canonical match (roof = any(...))
      or cl.category = any (c.categories)
      -- keyword match: the description against the pro's custom services
      -- (any category — homeowners bucket jobs imperfectly)
      or (
        cl.issue_description is not null
        and exists (
          select 1
          from unnest(c.categories) as svc
          where
            -- only custom services (not one of the canonical categories)
            svc <> all (array[
              'roof','plumbing','electrical','hvac','structural',
              'remodeling','landscaping','cleaning','windows','painting','other'
            ])
            and length(btrim(svc)) >= 3
            and (
              -- the service phrase appears in the homeowner's description …
              cl.issue_description ilike '%' || svc || '%'
              -- … or it's a close fuzzy match (handles plurals / word forms)
              or word_similarity(lower(svc), lower(cl.issue_description)) > 0.4
            )
        )
      )
    )
    and not exists (
      select 1 from lead_applications la
      where la.lead_id = cl.id and la.contractor_id = c.id
    )
  order by cl.created_at desc;
$$;


-- =====================================================================
-- file: supabase/migrations/0016_contractor_ratings.sql
-- =====================================================================
-- =============================================================================
-- Hearth — keep a contractor's rating in sync with their reviews.
--
-- Homeowners leave reviews (0009 reviews table), but contractors.rating was
-- static (seeded demo values). This adds a review_count column and a trigger
-- that recomputes rating (average, 1 decimal) + review_count whenever a review
-- is inserted / updated / deleted. The UI shows the rating only when
-- review_count > 0, so seeded values are never displayed as if they were real.
-- =============================================================================

alter table public.contractors
  add column if not exists review_count int not null default 0;

-- Recompute one contractor's aggregate from the reviews table. SECURITY DEFINER
-- because the homeowner writing the review doesn't own the contractor row.
create or replace function public.recompute_contractor_rating(p_contractor uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update public.contractors c
     set rating       = sub.avg_rating,
         review_count = sub.cnt
    from (
      select round(avg(rating)::numeric, 1) as avg_rating,
             count(*)                        as cnt
      from public.reviews
      where contractor_id = p_contractor
    ) sub
   where c.id = p_contractor;
$$;

-- Fire on any change to a review; refresh the affected contractor(s).
create or replace function public.reviews_sync_rating()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (tg_op = 'DELETE') then
    perform public.recompute_contractor_rating(old.contractor_id);
    return old;
  end if;
  perform public.recompute_contractor_rating(new.contractor_id);
  -- An update that re-points the review to a different contractor refreshes both.
  if (tg_op = 'UPDATE' and new.contractor_id is distinct from old.contractor_id) then
    perform public.recompute_contractor_rating(old.contractor_id);
  end if;
  return new;
end;
$$;

drop trigger if exists reviews_sync_rating on public.reviews;
create trigger reviews_sync_rating
  after insert or update or delete on public.reviews
  for each row execute function public.reviews_sync_rating();

-- Backfill from any reviews that already exist. Contractors with no reviews keep
-- review_count = 0 (their seeded rating simply won't be shown by the UI).
update public.contractors c
   set rating       = sub.avg_rating,
       review_count = sub.cnt
  from (
    select contractor_id,
           round(avg(rating)::numeric, 1) as avg_rating,
           count(*)                        as cnt
    from public.reviews
    group by contractor_id
  ) sub
 where c.id = sub.contractor_id;


-- =====================================================================
-- file: supabase/migrations/0017_review_integrity.sql
-- =====================================================================
-- =============================================================================
-- Hearth — review integrity. Only the real homeowner can review the actual pro
-- who did their job, exactly once.
--
-- Before this, the insert trusted lead_id + contractor_id from the client and
-- only checked can_access_lead(), so:
--   * a homeowner could attribute a review to ANY contractor_id (sabotage a
--     competitor) on a lead they own;
--   * an assigned contractor could self-review;
--   * anyone could leave unlimited reviews on one job (rating manipulation).
--
-- Now reviews go through leave_review(), a SECURITY DEFINER function that derives
-- the contractor from the lead, verifies the caller owns the job's property, and
-- enforces one review per job. Direct inserts are no longer allowed by RLS.
-- =============================================================================

-- One review per job. Drop any pre-existing duplicates first (keep one).
delete from public.reviews a
  using public.reviews b
 where a.lead_id = b.lead_id
   and a.ctid < b.ctid;
create unique index if not exists reviews_lead_unique
  on public.reviews (lead_id);

-- The only sanctioned way to leave a review. Everything is derived/verified
-- server-side; nothing about who is reviewed is taken from the caller.
create or replace function public.leave_review(
  p_lead uuid, p_rating smallint, p_comment text
) returns void
language plpgsql security definer set search_path = public as $$
declare
  v_contractor uuid;
  v_property   uuid;
begin
  if p_rating is null or p_rating < 1 or p_rating > 5 then
    raise exception 'Rating must be between 1 and 5';
  end if;

  select contractor_id, property_id
    into v_contractor, v_property
    from contractor_leads
   where id = p_lead;

  if v_property is null then
    raise exception 'Job not found';
  end if;
  -- Only the homeowner who owns the job's property can review it.
  if not public.owns_property(v_property) then
    raise exception 'You can only review your own job';
  end if;
  -- And only once a pro was actually assigned to that job.
  if v_contractor is null then
    raise exception 'No pro was assigned to this job';
  end if;

  insert into public.reviews (lead_id, contractor_id, property_id, rating, comment)
    values (p_lead, v_contractor, v_property, p_rating, nullif(btrim(p_comment), ''))
  on conflict (lead_id) do update
    set rating     = excluded.rating,
        comment    = excluded.comment,
        created_at = now();
end;
$$;

-- Block direct inserts — the function above is the only path in.
drop policy if exists "reviews insert" on public.reviews;


-- =====================================================================
-- file: supabase/migrations/0018_review_views.sql
-- =====================================================================
-- =============================================================================
-- Hearth — let homeowners read a contractor's reviews when choosing a pro.
--
-- The reviews RLS only lets a homeowner read reviews on their OWN leads, so they
-- couldn't read an applicant's track record. This adds contractor_reviews(), a
-- SECURITY DEFINER function that returns only the safe, public columns (rating,
-- comment, date) for a contractor — never the lead/property that links a review
-- back to a specific homeowner.
-- =============================================================================

create or replace function public.contractor_reviews(p_contractor uuid)
returns table (
  rating     smallint,
  comment    text,
  created_at timestamptz
)
language sql
security definer
stable
set search_path = public
as $$
  select rating, comment, created_at
  from public.reviews
  where contractor_id = p_contractor
  order by created_at desc
  limit 100;
$$;

